<!DOCTYPE html>
<html>
<head>
	<title>planted</title>
</head>
<body bgcolor="black">
<h1></h1>
<img src="plant.jpg" height="400" width="1300">
<h2 style="color: orange">Articles</h2>
<h1 style="color: green">Planning a Planted Aquarium</h1>
<p style="color: red; font-size: 20px ">Planted tanks are a popular and rapidly growing segment of the aquarium hobby, one that allows hobbyists to combine the beauty of nature with the benefits of a balanced ecosystem. Unlike a traditional aquarium, live plants are the primary focus, with fish being an accent or compliment to the overall effect. </p>
<h2 style="color: orange">Benefits of Live Plants in an Aquarium:</h2>
<li style="color: red;font-size: 18px">They enhance water quality and help prevent algae growth by using nutrients produced by fish waste, uneaten food and organic debris.</li>
<li style="color: red; font-size: 18px">They produce oxygen during daylight hours, which is used by fish and helps stabilize pH. Fish, in turn, release CO₂, which plants use as a food source.</li>
<li style="color: red; font-size: 18px">Fish tend to feel safe which encourages them to stay out in the open and develop more vivid colors.</li>
<li style="color: red;font-size: 18px">Plants encourage many types of fish to spawn and give newly-hatched fry a place to hide while they grow.</li>
<h2 style="color: orange">Planning a Planted Aquarium:</h2>
<p style="color: red; font-size: 20px ">Planted tanks are less work to maintain than conventional aquariums, but they require proper planning. Special attention should be paid to tank dimensions, lighting, substrate, fertilizers and choice of plant and fish species. A well-planned and maintained planted aquarium will provide years of enjoyment and relaxation. Let’s get started!</p>
<h2 style="color: orange">Selecting an Aquarium for Live Plants</h2>
<p style="color: red; font-size: 20px ">Consider the types of plants – and fish – you want to keep and then choose an aquarium that best suits their needs. Almost any sized aquarium can be used to set up a planted tank, however taller tanks require stronger lighting for certain plant species. Aqueon offers a  wide range of aquarium sizes suitable for planted displays.</p>
<h2 style="color: orange">Planted Aquarium Lighting</h2>
<p style="color: red; font-size: 20px ">The key to success with aquatic plants is using the correct light intensity and spectrum. The spectral output should be between 6500 and 8000 Kelvin. Intensity depends on plant species and water depth. Aqueon OptiBright® MAX and OptiBright®+ LED lights offer the desired spectrum for aquatic plants, along with dimming capabilities and automatic sunrise/sunset to mimic a natural day/night cycle. Aqueon’s Clip-On Planted Aquarium LED light is designed for small aquariums up to 20 gallons.The term “watts per gallon” is often used for choosing the best light for a planted aquarium. Watts describe how much electricity a light uses, not how much light energy it produces. While not entirely accurate, it is a useable formula with standard fluorescent lights. With the introduction of HO T5 and LED lighting, this comparison no longer works across different lighting platforms. PAR (photosynthetically active radiation) is a better way of rating aquarium lighting for plants. Aquatic plants can be divided into low, medium and intense light-requiring groups. If you’re adding plants to an existing aquarium, ask your local aquatic store expert to recommend plants that are compatible with the light you have. The alternative is to choose the plants you want to grow and purchase a light that meets their needs. Be sure to exchange standard fluorescent and HO T5 bulbs with aquarium plant-specific bulbs and replace the bulbs every 10 to 12 months</p>
<h2 style="color: orange">Substrate for a Planted Aquarium</h2>
<p style="color: red; font-size: 20px ">Choosing the proper substrate is essential for success with rooted plants. Coarse sand or fine gravels work best. Avoid pebbles or large, chunky gravel (a little here and there is OK for accent, but not as the main substrate). Several plant-specific substrates are available that are infused with iron and other minerals to promote healthy plant growth. Some have the added benefit of buffering pH and softening water, both of which are desirable for many plant species. You can also use standard aquarium sand or fine gravel and add plant nutrient tablets where needed, or layer/mix it with plant-specific substrates. Do not use coral or dolomite substrates, as they slowly dissolve and may raise pH and alkalinity above desirable levels. </p>
<h2 style="color: orange">Planted Aquarium Water Chemistry</h2>
<p style="color: red; font-size: 20px ">Water chemistry is important to plants. In general, they do best in moderately soft water at a pH between 6.8 and 7.8. If your tap water is exceptionally hard or has a high pH, consider using reverse osmosis or deionized water with trace minerals and buffers added. </p>
<h2 style="color: orange">Nutrients and Fertilizers for a Planted Aquarium</h2>
<p style="color: red; font-size: 20px ">Aquatic plants use iron, magnesium and potassium as well as other macro and micro-nutrients to grow and develop their best colors. Some plants feed primarily through their leaves, while others are root-feeders. Some plants do both. Use an enriched plant substrate when setting up your aquarium for root feeders or insert fertilizer tablets around the roots on a regular basis. Dose liquid fertilizers such as Aqueon Plant Food weekly for leaf-feeders. Do not use liquid fertilizers that contain copper if you keep decorative snails or dwarf shrimp, as copper can be harmful to them. </p>
<h2 style="color: orange">Planted Aquariums and CO2</h2>
<p style="color: red; font-size: 20px ">In addition to minerals and fertilizers, plants also use carbon to grow. The use of CO2 can be a significant commitment, but its effect on plant growth and color is dramatic and well worth the effort. Automated systems are the easiest to use, but more affordable DIY systems are not difficult to build. Liquid carbon supplements are also available. When adding CO2 or liquid carbon, it may be necessary to increase liquid and tablet nutrient dosing to keep up with more rapid plant growth. 
</p>
<h2 style="color: orange">Live Plant Selection For a Planted Aquarium</h2>
<p style="color: red; font-size: 20px ">A planted aquarium is living art, and designing the layout requires careful thought and planning. Draw a rough sketch of the plant and hardscape – rocks and driftwood – layout. Once you’ve installed the hardscape, start in back with tall plants such as Vallisneria or Sagittaria grasses, or stem plants that grow rapidly. Use showy species like Amazon Swords, large Anubias or tiger lilies in the middle and low-profile plants like short Cryptocorynes, dwarf Anubias, mosses or baby tears in the foreground. Leave enough space around large broadleaf species to prevent them from blocking light to smaller plants as they grow. </p>
<h2 style="color: orange">Fish Selection for Planted Aquarium</h2>
<p style="color: red; font-size: 20px ">As mentioned, fish are an accent in a planted aquarium, not the main feature. Choose species that complement the overall feel and character of the tank. In smaller aquariums, schooling fish like tetras or rasboras are good choices, along with rams and Apistogramma dwarf cichlids. For medium to larger sized aquariums, consider Congo Tetras, Kribensis or a collection of Rainbowfishes. Discus and Angelfish make excellent choices for aquariums of 100 gallons or more. Bottom cleaners can include Corydoras catfish, Otocinclus and certain species of loaches. Avoid herbivorous fish like Tinfoil Barbs, Silver Dollars, and plecostomus as they will eat your plants!</p>
<h2 style="color: orange">Finding Balance in a Planted Aquarium</h2>
<p style="color: red; font-size: 20px ">When you first set up an aquarium there is no biological balance. This takes weeks, if not months to achieve, and in the meantime, things may not go perfectly.Planted aquariums are no different and, in fact, can be further complicated by using fertilizers, CO2 and strong lighting. Strong light produces rapid plant growth, which in turn, puts an increased demand on fertilizers and CO2. Adding too much fertilizer can cause algae blooms, and too much CO2 can cause fluctuations in pH.The best approach is to start slowly, add nutrients in small amounts and be patient. If you make changes, make them minor and allow at least 2 weeks to evaluate the effects. Be consistent, put your lights on a timer, dose nutrients faithfully and don’t make sudden drastic changes to the system. Take notes and keep a log of any changes in dosing, daylight hours, etc. Eventually your planted aquarium will find balance and go on auto-pilot.Setting up a planted aquarium is a wonderful way to bring a piece of nature into your home or workplace. With good planning and consistent maintenance, the benefits can last a lifetime!</p>
</body>
</html>